INSERT INTO DBMOBILE.TB_MEDSUS_CATEGORIA (CO_CATEGORIA, NO_CATEGORIA, CO_TIPO_CATEGORIA, DS_CATEGORIA)
VALUES(1, 'Básico', 1, NULL);

INSERT INTO DBMOBILE.TB_MEDSUS_CATEGORIA (CO_CATEGORIA, NO_CATEGORIA, CO_TIPO_CATEGORIA, DS_CATEGORIA)
VALUES(2, 'Estratégico', 1, NULL);

INSERT INTO DBMOBILE.TB_MEDSUS_CATEGORIA (CO_CATEGORIA, NO_CATEGORIA, CO_TIPO_CATEGORIA, DS_CATEGORIA)
VALUES(3, 'Especializado', 1, NULL);

INSERT INTO DBMOBILE.TB_MEDSUS_CATEGORIA (CO_CATEGORIA, NO_CATEGORIA, CO_TIPO_CATEGORIA, DS_CATEGORIA)
VALUES(4, 'Farmácia Popular do Brasil', 1, NULL);