INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (1,'CATMAT',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (2,'MEDICAMENTO',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (3,'FORMA FARMACÊUTICA',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (4,'GRUPO',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (5,'CID ou DOENÇA',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (6,'DOCUMENTOS NECESSÁRIOS',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (7,'COMO ACESSAR - REGRAS ',1,'N','N');
INSERT INTO "DBMOBILE".TB_MEDSUS_CAMPO (CO_SEQ_CAMPO,DS_CAMPO,CO_TIPO_CAMPO,ST_OBRIGATORIO,ST_PADRAO) VALUES (8,'ONDE ENCONTRAR',1,'N','N');
