INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(1, 'MEDICAMENTO', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(2, 'FORMA FARMACÊUTICA', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(3, 'GRUPO', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(4, 'CID ou DOENÇA', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(5, 'DOCUMENTOS NECESSÁRIOS', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(6, 'COMO ACESSAR - REGRAS ', 1, 'N', 'N');

INSERT INTO DBMOBILE.TB_MEDSUS_CAMPO (CO_SEQ_CAMPO, DS_CAMPO, CO_TIPO_CAMPO, ST_OBRIGATORIO, ST_PADRAO)
VALUES(7, 'ONDE ENCONTRAR', 1, 'N', 'N');